# Generated by Django 4.0.3 on 2022-03-12 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['c_time'], 'verbose_name': '用户管理', 'verbose_name_plural': '用户'},
        ),
    ]
