# Generated by Django 4.0.3 on 2022-03-12 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['c_time'], 'verbose_name': '用户', 'verbose_name_plural': '用户管理'},
        ),
    ]
